import Head from 'next/head'
import styles from '../styles/Home.module.css'
import CssBaseline from '@material-ui/core/CssBaseline';
import Layout from '../components/Layout';
import MainPage from '../components/MainPage';
const cards = [1, 2, 3, 4, 5, 6, 7, 8, 9];

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Porfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
      <CssBaseline />
      <Layout>
        <MainPage />
      </Layout>
      
    </>
    </div>
  )
}
